create database GeneratorDataBase;
use GeneratorDataBase;

CREATE TABLE [dbo].[table1](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](6) NOT NULL,
 CONSTRAINT [PK_table1_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO;

CREATE TABLE [dbo].[table2](
	[ID] [int] NOT NULL,
	[AutoIncrementColumn] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_table2] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];